### ISSUE TITLE
task1 `cargo +nightly` toolchain not available

### ISSUE THREAD

**Issue by salameme** [ls1-sys-prog-course/docs#2]
# CI Log:

```
📝 Build


  cargo +nightly build --release
error: toolchain 'nightly-x[8](https://github.com/ls1-sys-prog-course/task1-syscalls-salameme/runs/6259686038?check_suite_focus=true#step:3:8)6_64-unknown-linux-gnu' is not installed
  make: *** [Makefile:13: all] Error 1
```

# Expected result:

As stated in the README, for the nightly toolchain to be available.

**Comment by dimstav23** [comment]
Due to the CI runners congestion, the actions sometimes are executed in the default Github CI which does not the nightly toolchain available. You can check whether this is the issue by looking the following action parts:
Github CI example:
![image](https://user-images.githubusercontent.com/15181592/166295074-ee03b694-dc75-4454-9d68-eb7b6186c630.png)
Sys-prog CI example:
![image](https://user-images.githubusercontent.com/15181592/166295654-a93fc882-5d3f-4a80-9dc8-699e87df6521.png)

To get rid of this issue, you can modify the auto-generated classroom.yml file of the repo and replace `ubuntu-latest` with `self-hosted`.

We are working on a permanent fix for this as there was no option to directly configure it in the Github classroom.

**Comment by salameme** [comment]
Thanks for the help! This worked perfectly for me, could a link to this issue be added to the `README.md` of `task1` and/or `docs` to help other students?

**Comment by sssemil** [comment]
> To get rid of this issue, you can modify the auto-generated classroom.yml file of the repo and replace ubuntu-latest with self-hosted.

This didn't work for me. I modified the Makefile the following way instead:
```Makefile
all: rust_nightly_toolchain
	$(CARGO) build --release

rust_nightly_toolchain:
	rustup toolchain install nightly
	rustup default nightly
```

**Comment by rgouicem** [comment]
This should be fixed for all subsequent tasks. We hardcoded the `classroom.yml` files of every task to use our self-hosted runners and never the GitHub runners.
